version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    container_name: maps_backend
    ports:
      - "8000:8000"
    volumes: 
      - ./backend/app:/app
    environment:
      - GOOGLE_API_KEY
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maps_frontend
    ports:
      - "80:80"
    tty: true
